//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Doctor.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.OrderCouponAccounts = new HashSet<OrderCouponAccount>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Email { get; set; }
        public string IDCard { get; set; }
        public string PhoneNumber { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Thumbnail { get; set; }
        public string ThumbnailIDCard { get; set; }
        public string ThumbnailLicense { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TokenFacebook { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string TokenLogin { get; set; }
        public Nullable<System.DateTime> ExpireTokenLogin { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Password { get; set; }
        public string DeviceToken { get; set; }
        public string TokenRegister { get; set; }
        public Nullable<System.DateTime> ExpireTokenRegister { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public Nullable<bool> VerifyPhone { get; set; }
        public Nullable<bool> VerifyEmail { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string TokenAutoLogin { get; set; }
        public Nullable<bool> IsBanned { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCouponAccount> OrderCouponAccounts { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
