//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Doctor.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Accounts = new HashSet<Account>();
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string thumbnail { get; set; }
        public string shortDesc { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> dateDelete { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> idCatProd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual CategoryProd CategoryProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
