//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Doctor.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> IDLang { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> IsParent { get; set; }
    }
}
