//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Doctor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCouponAccount
    {
        public int AccountID { get; set; }
        public int OrderID { get; set; }
        public int CouponID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Order Order { get; set; }
    }
}
