//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Doctor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderCouponAccounts = new HashSet<OrderCouponAccount>();
            this.OrderStatus = new HashSet<OrderStatu>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> idOrderType { get; set; }
        public Nullable<int> idOrderStatus { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> totalPay { get; set; }
        public Nullable<decimal> buyerEndingBalance { get; set; }
        public Nullable<decimal> receiveEndingBalance { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<int> idBuyer { get; set; }
        public Nullable<int> idReceive { get; set; }
        public Nullable<int> idProduct { get; set; }
        public string card_fullname { get; set; }
        public string card_number { get; set; }
        public string card_bank { get; set; }
        public string note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCouponAccount> OrderCouponAccounts { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatu> OrderStatus { get; set; }
    }
}
